version: 0.0
os: linux
files:
  - source: /web-config/challenge.service
    destination: /etc/systemd/system
  - source: /web-config/default
    destination: /etc/nginx/sites-available
  - source: /
    destination: /srv/challenge-website
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server
  #     timeout: 300
  #     runas: root