version: 0.2
env:
  shell: bash
phases:
  build:
    commands:
      - git log --oneline
      - echo "update version file"
      - |-
        git describe --exact-match --abbrev=0 --tags > version.txt || \
        git rev-parse --short=7 HEAD > version.txt
      - cat version.txt
artifacts:
  files:
    - '**/*'
