name: flask demo app

on:
  push:

jobs:
  flask pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Source
        uses: actions/checkout@v3
      - name: Build
        run: python install -r requirements.txt