name: flask demo app

on:
  push:

jobs:
  flask_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Source
        uses: actions/checkout@v3
      - name: Build
        run: pip install -r requirements.txt